spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://ec2-3-248-4-172.eu-west-1.compute.amazonaws.com:5432/d5c4vphe1vsm5o?sslmode=disable
    username: mhzlihprhnmclt
    password: cddb239d5d1708ca93521645f468132ee1719f603d22bf4b51cf779b8253c08f
    driverClassName: org.postgresql.Driver

