spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://ec2-54-217-213-79.eu-west-1.compute.amazonaws.com:5432/d7k7v3h3fooao?sslmode=require
    username: twalvkyanjnxuz
    password: ef67173560124532e6733872393b1f10664358fbab94c2aac8a947d2938b856f
    driverClassName: org.postgresql.Driver